### ISSUE TITLE
[Renderer] Roadmap

### ISSUE THREAD

**Issue by hzqst** [hzqst/MetaHookSv#416]
- [ ] Take control over all native OpenGL calls
  - [ ] efxapi
  - [ ] BaseUISurface
  - [ ] EngineSurface
  - [ ] studioapi
  - [ ] Texture unit management
    - [ ] GL_Bind
    - [ ] GL_SelectTexture
    - [ ] GL_GenTexture
    - [ ] GL_FreeGLTex
    - [ ] GL_EnableMultitexture
    - [ ] GL_DisableMultitexture
  - [ ] Draw 2D
    - [ ] SPR_Set
    - [ ] Draw_Pic 
    - [ ] Draw_AlphaSubPic 
    - [ ] Draw_AlphaPic 
    - [ ] Draw_AlphaAddPic 
    - [ ] Draw_Pic2
    - [ ] Draw_TransPicTranslate
    - [ ] Draw_Frame
    - [ ] Draw_SpriteFrameHoles
    - [ ] Draw_SpriteFrameAdditive
    - [ ] Draw_SpriteFrameGeneric
    - [ ] Draw_FillRGBA
    - [ ] Draw_FillRGBABlend
    - [ ] Draw_FadeScreen
    - [ ] GL_Set2D
    - [ ] R_PolyBlend
    - [ ] CVideoMode_Common::DrawStartupGraphic
  - [ ] Draw 3D
    - [ ] R_DrawParticles
    - [ ] R_BeamDrawList
    - [ ] R_StudioXXX
  - [ ] Texture Loader
    - [ ] GL_LoadFilterTexture
    - [ ] R_InitParticleTexture
    - [ ] BaseUISurface::DeleteTextureByID
  - [ ] Misc
  - [ ] R_Envmap_f
  - [ ] R_TimeRefresh_f
  - [ ] SCR_ScreenShot_f
  - [ ] D_FillRect
  - [ ] CheckTextureExtensions
  - [ ] GL_Init
  - [ ] GL_SetMode
  - [ ] VID_TakeSnapshotRect
  - [ ] CGame::CreateGameWindow
  - [ ] V_RenderView-> `qglClearColor( 0, 0, 0, 0 ); qglClear( GL_COLOR_BUFFER_BIT );`
- [ ] Port to OpenGL 4.3 Core Profile
- [ ] Port to OpenGL 4.1 Core Profile
- [ ] Port the renderer backend from native OpenGL to DiligentEngine

**Comment by hzqst** [comment]
TODO:

**Comment by hzqst** [comment]
```cpp
m_pImmediateContext->BeginRenderPass(RPBeginInfo);

for(auto pCommand : m_CommandList[0]){
 pCommand->Commit();
  pCommand ->Destroy();
}

**Comment by hzqst** [comment]
CDiligentLambaCommand
